# Generated by Django 4.2 on 2023-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
